### ISSUE TITLE
sky-dropdown-menu doesn't display in Internet Explorer when it contains only 1 sky-dropdown-item

### ISSUE THREAD

**Issue by Blackbaud-ChrisReid** [blackbaud/skyux-popovers#123]
### Expected behavior
A sky-dropdown-menu component should be visible when expanded regardless of the number of items contained.

### Actual behavior
When using internet explorer, the expanded menu of a dropdown is not visible, though inspecting the html of the page shows that the sky-dropdown-menu is expanded. 

### Steps to reproduce
1. Create a sky-dropdown-menu containing a single sky-dropdown-item
2. View the page that the dropdown in on in Internet Explorer
3. Expand the dropdown
4. Observe that the dropdown is not visible

### Severity
Medium

### Impact
Medium

[AB#1583242](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1583242)

**Comment by Blackbaud-KerryCampbell** [comment]
With the end of support for IE later this year by Microsoft we are holding on resolving any IE issues that are not critically impacting users.  Users should be instructed to move to a modern browser.
