### ISSUE TITLE
adding item to dropdown on sky-list-secondary-action results in console error and menu getting frozen open

### ISSUE THREAD

**Issue by Blackbaud-TomSisson** [blackbaud/skyux-popovers#137]
### Expected behavior
We are conditionally adding a menu item to the `sky-list-secondary-action` menu of a `sky-list-toolbar`. We expect the `unshift()` method to add this item to the top of the list and for the list to go away once something is selected.

### Actual behavior
We are intermittently seeing the menu item stay at the bottom of the list and the `sky-list-secondary-action` menu gets frozen in the open state. We are seeing the following error in the console: 
> TypeError: Cannot read property 'reaffix' of undefined
>    at SkyDropdownComponent.handleIncomingMessages (dropdown.component.ts:434)
>    at SafeSubscriber.eval [as _next] (dropdown.component.ts:254)
>    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)

This appears to be related to the `sky-list-secondary-action` menu as I was not able to reproduce this in StackBlitz on a `sky-dropdown` menu.

When I set breakpoints in the dropdown.component.ts file it appears as though the `handleIncomingMessages()` method is being called twice. When it gets called for the Reposition, `isOpen` is true but the `this.affixer` object hasn't yet been created.

### Steps to reproduce
- Load this [StackBlitz example](https://stackblitz.com/edit/angular-rzfbra?devtoolsheight=33&file=src/app/list-toolbar-demo.component.ts)
- Click on the Add Secondary Action Menu Item button at the top of the page 
- Click on the More button
- Error: Cannot read property 'reaffix' of undefined
- Menu remains open even if you click on the More button again or select an action

### Severity
Medium

### Impact
Medium

[AB#1695603](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1695603)

**Comment by Blackbaud-KerryCampbell** [comment]
tracking in ADO item [1695602](https://blackbaud.visualstudio.com/Products/_workitems/edit/1695602)
