### ISSUE TITLE
Dropdown is constrained by modal in iOS

### ISSUE THREAD

**Issue by Blackbaud-RobertDixon** [blackbaud/skyux-popovers#15]
A `<sky-dropdown>` in a modal is covered up by the modal footer in SKYUX2 on an iOS browser.  Duplicated in an iPhone X in the following image:
![image](https://user-images.githubusercontent.com/25301661/55835085-456a8780-5ae9-11e9-9ba8-1bcc4a98eca1.png)

I didn't have any relevant .scss / css affecting this, and the HTML for the dropdown was pretty straightforward:

```
        <sky-dropdown>
            <sky-dropdown-button>
                {{ selection.title }}
            </sky-dropdown-button>
            <sky-dropdown-menu>
                <sky-dropdown-item *ngFor="let range of ranges">
                    <button type="button" (click)="selectionChanged(range)">
                        {{ range.title }}
                    </button>
                </sky-dropdown-item>
            </sky-dropdown-menu>
        </sky-dropdown>
```

I'm going to attempt to work around the issue by changing our particular dropdown to use an HTML select instead, but I was advised to file this issue anyway so the SKYUX team can be made aware.

**Comment by Blackbaud-AlexKingman** [comment]
Thanks for filing this issue @Blackbaud-RobertDixon. We were unable to replicate this with a simple testing SPA. We tried both SKYUX2 `2.47.0` (current as of 4/18/19) and `2.39.0` (what your SPA was using). Also tried this on an iPhone X and iPhone 8 with no luck. I'll take a look at your SPA to see if there is anything that might be impacting the positioning and/or z-index rules. In the meantime, would you be able to replicate this with a simple SPA? That would help us better troubleshoot what's going on here.
Thanks again!

**Comment by Blackbaud-AlexKingman** [comment]
Possibly related to blackbaud/skyux-datetime#43

**Comment by Blackbaud-AlexKingman** [comment]
We found there was a conflicting `position: relative` on the consumer code that was conflicting with the modal's positioning. Removing that has fixed this issue. Closing ticket.
