### ISSUE TITLE
Dropdown with enough items to exceed height of window instead takes up the full window

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-popovers#16]
@Blackbaud-StewartStephens commented on [Thu Nov 01 2018](https://github.com/blackbaud/skyux2/issues/2165)

### Expected behavior
I'm not sure exactly what this should look like, but I've gotten a few reports (internal) about this where people are interpreting it as a bug.

### Actual behavior
If a dropdown has enough items that they would exceed the height of the window, it enters a full-screen mode which extends nearly to the end of the page both horizontally and vertically.  There is also a little header space and an X close button, which leads me to believe that this was a design choice.

### Steps to reproduce
Make a dropdown with a lot of items.

### Plunker:
https://plnkr.co/edit/q5r8fjfEBFvuRBeuBpSB?p=preview

### Severity
Low

### Impact
Low

---

@Blackbaud-AlexKingman commented on [Wed Nov 07 2018](https://github.com/blackbaud/skyux2/issues/2165#issuecomment-436782676)

@Blackbaud-StewartStephens Thanks for brining this up. The dropdown is indeed working as designed. The dropdown component is meant to display a set of actions or functions. Generally when there are enough of these to cause it to enter a full-screen modal, it might be an indicator that we're using the wrong component. There might be a more effective selection input to use in this case - for example, the select or lookup components. I'd suggest taking a look at this guide to help determine the best fit: https://developer.blackbaud.com/skyux/design/guidelines/form-design#selection-inputs

I'm going to go ahead and close this as "working as designed". If you have additional questions/concerns, feel free to re-open. Thanks!

---

@Blackbaud-SteveBrush commented on [Fri May 10 2019](https://github.com/blackbaud/skyux2/issues/2165#issuecomment-491360625)

Reopening since this came up recently.

**Comment by Blackbaud-SteveBrush** [comment]
Related: https://github.com/blackbaud/skyux-lookup/issues/18

**Comment by Blackbaud-AlexKingman** [comment]
Duplicate issue - closing. For future tracking, this will be addressed in blackbaud/skyux-popovers#36. This is also heavily related to blackbaud/skyux-lookup#18, which we'll leave open until the PR is complete.
