### ISSUE TITLE
Dropdowns cannot be dismissed using Escape when in a modal

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-popovers#25]
### Expected behavior
When a dropdown is in a modal, it should be able to be closed/dismissed using the Escape key.

### Actual behavior
Using the Escape key causes the modal to close.

### Steps to reproduce
Try out this demo
https://stackblitz.com/edit/dropdown-modal-accessibility

### Severity
Low

### Impact
Low

**Comment by Blackbaud-SteveBrush** [comment]
We will need to check autocomplete's implementation once we create a fix, since autocomplete uses dropdown under the hood.

**Comment by Blackbaud-SteveBrush** [comment]
Issue moved to [blackbaud/skyux-modals #60](https://github.com/blackbaud/skyux-modals/issues/60) via [**ZenHub**](https://www.zenhub.com/)
