### ISSUE TITLE
Popover appears under chrome scrollbar

### ISSUE THREAD

**Issue by jeffbdye** [blackbaud/skyux-popovers#27]
### Expected behavior
Popover appears over chrome vertical scrollbar

### Actual behavior
Popover is underneath the scrollbar, content in the popover is hidden by the scrollbar.

### Steps to reproduce
Open the modal, click on the popover on the far right hand side:
https://stackblitz.com/edit/angular-4ftraz?file=src%2Fapp%2Fdemo%2Fmodal.component.html

![image](https://user-images.githubusercontent.com/4132425/62735439-2b8a7400-b9f9-11e9-81d1-6f831b6f773c.png)

### Severity
Cosmetic

### Impact
Cosmetic

**Comment by jeffbdye** [comment]
Appears in Chrome 76.0.3809.100, but not latest Firefox or Edge.

**Comment by Blackbaud-TrevorBurch** [comment]
Fixed via `skyux/modals` version `3.1.2`
