### ISSUE TITLE
Dropdown menu does not show when using component inside a toolbar on mobile

### ISSUE THREAD

**Issue by blackbaud-jeremymorgan** [blackbaud/skyux-popovers#43]
Dropdown menu does not show when using component inside a toolbar on mobile

### Expected behavior
Dropdown opens as usual

### Actual behavior
Dropdown button goes into a :hover state, but no dropdown menu shows.

### Steps to reproduce
1. Create a regular sky toolbar
2. Put a dropdown component inside toolbar
3. Open in mobile.
4. See menu not display

### Severity
Low-Medium - prevent access to a few actions in mobile

### Impact
Medium

**Comment by Blackbaud-SteveBrush** [comment]
Closing since this appears to work on the latest versions of `@skyux/layout` and `@skyux/popovers`.
